# Generated by Django 5.1.2 on 2025-02-04 12:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('employee', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('start_time', models.TimeField(default='00:00', verbose_name='inicio')),
                ('end_time', models.TimeField(blank=True, default='00:00', null=True, verbose_name='fin')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='client.client', verbose_name='cliente')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee.employee', verbose_name='empleado')),
                ('services', models.ManyToManyField(related_name='appointments', to='service.service', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'cita',
                'ordering': ['start_time', 'client'],
                'indexes': [models.Index(fields=['start_time'], name='appointment_start_t_9ed8bd_idx')],
            },
        ),
    ]
