# Generated by Django 5.1.2 on 2025-02-04 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('client', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total servicios')),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('visa', 'Tarjeta')], default='visa', max_length=8, verbose_name='modo de pago')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment', verbose_name='cita')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='cliente')),
                ('services', models.ManyToManyField(blank=True, related_name='transactions', to='service.service', verbose_name='servicios')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='sales_trans_date_402b02_idx'), models.Index(fields=['client'], name='sales_trans_client__4be22e_idx')],
            },
        ),
    ]
