# Generated by Django 5.1.2 on 2025-02-04 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'producto',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('movement_type', models.CharField(blank=True, choices=[('increase', 'Aumento'), ('decrease', 'Reducción')], max_length=8, null=True, verbose_name='tipo de movimiento')),
                ('reason', models.CharField(choices=[('cabin_expense', 'Gasto en cabina'), ('sale', 'Venta'), ('disrepair', 'Mal estado'), ('increase stock', 'Aumento de stock')], max_length=16, verbose_name='motivo de gasto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movement', to='stock.product', verbose_name='producto')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stock.supplier', verbose_name='proveedor'),
        ),
    ]
